# Group by and Aggregate Functions

Simple exercise based on [https://github.com/AlexTheAnalyst/PandasYouTubeSeries](https://github.com/AlexTheAnalyst/PandasYouTubeSeries)

*Visualisation Tip*
If you prefer the Jupyter Notebook render over VS Code's data wrangler, you can disable the `data wrangler output viewer` option in the settings. 
See [https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html](https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html) for more details.

In [26]:
## As always, import pandas as ...

import pandas as pd

In [27]:
## Read CSV from GitHub url: https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true

df = pd.read_csv("https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true")

In [28]:
## Explore the data
df.head()
df.shape
df.info
df
## Success? Commit changes to the repository!

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [29]:
## Let's group by Base Flavor

df.groupby("Base Flavor").mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [30]:
## Make this a new datafram
grouped_df = df.groupby("Base Flavor")

## Success? Commit changes to the repository!

In [31]:
## Let's count the number of flavors for each Base Flavor
grouped_df.count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [32]:
## Let's get the means for each Base Flavor
grouped_df = df.groupby("Base Flavor")
grouped_df.mean(numeric_only=True)

## Success? Commit changes to the repository!

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [33]:
## Let's try that in one line
df.groupby("Base Flavor").mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [34]:
## Let's discover some popular aggregate statistics like count, sum, min, max. Notice that text columns will appear with min and max as well

grouped_df.min()


## Success? Commit changes to the repository!

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [35]:
grouped_df.sum(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [36]:
grouped_df.agg(['count', 'sum', 'min', 'max'])

            Flavor                                                     \
             count                                                sum
Base Flavor
Chocolate        3          ChocolateRocky RoadChocolte Fudge Brownie
Vanilla          6  Mint Chocolate ChipVanillaCookie DoughPistachi...

                                     Liked                             \
                     min         max count              sum  min  max
Base Flavor
Chocolate      Chocolate  Rocky Road     3        YesYesYes  Yes  Yes
Vanilla      Cake Batter     Vanilla     6  YesNoYesNoYesNo   No  Yes

            Flavor Rating                  Texture Rating                  \
                    count   sum  min   max          count   sum  min  max
Base Flavor
Chocolate               3  25.2  8.2   8.8              3  21.7  7.0  7.6
Vanilla                 6  34.2  2.3  10.0              6  33.9  3.4  8.0

            Total Rating
                   count   sum   min   max
Base Flavor
Chocolate              3  47.1  15.2  16.6
Vanilla                6  68.1   5.7  18.0

In [37]:
df.columns

Index(['Flavor', 'Base Flavor', 'Liked', 'Flavor Rating', 'Texture Rating',
       'Total Rating'],
      dtype='str')

In [38]:
## Let's try more advanced aggregation with the `agg` function
## We have to specify which columns we want to aggregate and which functions to apply to them via a dictionary

grouped_df.agg({
    "Flavor Rating": ["mean", "min", "max"],
    "Texture Rating": ["mean", "min", "max"],
    "Total Rating": ["sum", "count"]
})

df

## Success? Commit changes to the repository!

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [39]:
## Let's group on multiple columns
## Check the dataframe again and group by Base Flavor and Liked (and show mean as value)
## Per Base Flavor, what is the average Flavor Rating among Liked 'yes' 'no'

df.groupby(["Base Flavor", "Liked"]).mean(numeric_only=True)

## Grouped the original dataframe (df) by Base Flavor and Liked. Then, calculated the mean. Got an error, becasue of strings. The, added the

multigrouped_df = df.groupby(['Base Flavor', 'Liked'])

In [40]:
# Do the multiple aggregation for Base Flavor and Liked ('mean', 'max', 'count', 'sum')

df.groupby(["Base Flavor", "Liked"]).agg({
    "Flavor Rating": ["mean", "min", "max"],
    "Texture Rating": ["mean", "min", "max"],
    "Total Rating": ["sum", "count"]
})

                  Flavor Rating            Texture Rating            \
                           mean  min   max           mean  min  max
Base Flavor Liked
Chocolate   Yes             8.4  8.2   8.8       7.233333  7.0  7.6
Vanilla     No              3.6  2.3   4.7       4.466667  3.4  5.0
            Yes             7.8  6.5  10.0       6.833333  6.0  8.0

                  Total Rating
                           sum count
Base Flavor Liked
Chocolate   Yes           47.1     3
Vanilla     No            24.2     3
            Yes           43.9     3

In [41]:
df.groupby(['Base Flavor', 'Liked']).agg({
    'Flavor Rating': ['mean', 'max', 'count', 'sum']
})

                  Flavor Rating
                           mean   max count   sum
Base Flavor Liked
Chocolate   Yes             8.4   8.8     3  25.2
Vanilla     No              3.6   4.7     3  10.8
            Yes             7.8  10.0     3  23.4

In [42]:
## Success? Commit changes to the repository!

In [43]:
## Let's disover an easier way to analyze the grouped data quickly
grouped_df.describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [44]:
## Success? Commit changes and push the repository to GitHub!